# Generated by Django 6.0.3 on 2026-03-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('especialista', 'Especialista')], max_length=20)),
                ('profissional', models.CharField(max_length=200)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('aguardando', 'Aguardando Marcação'), ('guia_disponivel', 'Guia Disponível'), ('realizado', 'Realizado')], default='solicitado', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
