# Generated by Django 6.0.3 on 2026-03-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0002_especialidade_procedimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='prioridade',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('preferencial', 'Preferencial')], default='normal', max_length=20),
        ),
    ]
