# Generated by Django 6.0.3 on 2026-03-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0003_remove_encaminhamento_tipo_encaminhamento_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='tipo',
            field=models.CharField(choices=[('especialista', 'Especialista'), ('exame', 'Exame')], default='exame', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encaminhamentos.procedimento'),
        ),
    ]
