# Generated by Django 6.0.3 on 2026-03-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0004_encaminhamento_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='especialidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encaminhamentos.especialidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo',
            field=models.CharField(choices=[('especialista', 'Especialista'), ('exame', 'Exame')], default='exame', max_length=20),
        ),
    ]
