# Generated by Django 6.0.3 on 2026-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0005_remove_encaminhamento_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='posicao_fila',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
