# Generated by Django 6.0.3 on 2026-03-14 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0006_encaminhamento_posicao_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
