# Generated by Django 6.0.3 on 2026-03-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0007_alter_encaminhamento_data_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aguardando', 'Aguardando Marcação'), ('guia_disponivel', 'Guia Disponível'), ('entregue', 'Entregue')], default='solicitado', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('encaminhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='encaminhamentos.encaminhamento')),
            ],
        ),
    ]
