# Generated by Django 6.0.3 on 2026-03-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0008_alter_encaminhamento_status_historicoencaminhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='resultados_exames/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('encaminhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='encaminhamentos.encaminhamento')),
            ],
        ),
    ]
