# Generated by Django 6.0.3 on 2026-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0009_anexoencaminhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='data_entregue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='data_resultado_disponivel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aguardando', 'Aguardando Marcação'), ('guia_disponivel', 'Guia Disponível'), ('entregue', 'Entregue'), ('resultado_disponivel', 'Resultado Disponível')], default='solicitado', max_length=20),
        ),
    ]
