# Generated by Django 6.0.3 on 2026-03-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0010_encaminhamento_data_entregue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoencaminhamento',
            name='tipo',
            field=models.CharField(choices=[('solicitacao', 'Solicitação'), ('resultado', 'Resultado do Exame'), ('outro', 'Outro Documento')], default='resultado', max_length=20),
        ),
    ]
